apiVersion: v1
data:
  mapRoles: |
    - groups:
        - system:bootstrappers
        - system:nodes
        username: system:node:{{EC2PrivateDNSName}}
        rolearn: # <role arn like this arn:aws:iam::111122223333:role/my-role>
  mapUsers: |
        - groups:
        userarn: #<our custom arn user>
        username: suresh
        userarn: #<our custom arn user>
        username: ramesh    
        - groups:
kind: ConfigMap  # run this cmd <kubectl get config aws-auth -n kube-system -o yaml> you will get config map details
metadata:
    creationTimestamp: 
    name: aws-auth
    namespace: kube-system
    uid: #<user id>
  
